FROM node:20

# Enable pnpm
RUN corepack enable

WORKDIR /app

# Copy everything
COPY . .

# Install dependencies
RUN pnpm install

# Build only API
WORKDIR /app/packages/api
RUN pnpm build

# Start API
CMD ["pnpm", "start"]
